name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-clang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-11, macos-10.15]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cmake CMakeLists.txt; make
      env:
        CC: clang
        CXX: clang++
  build-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-11, macos-10.15]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cmake CMakeLists.txt; make
      env:
        CC: gcc
        CXX: g++
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    steps:
    - name: Install SQLite3
      shell: pwsh
      run: choco install sqlite
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      shell: pwsh
      run: cmake CMakeLists.txt; make
      env:
        CC: msvc
        CXX: msvc
